create table Person
(
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null unique,
    birth_year int not null
);

insert into Person (full_name, birth_year)
values('John', 1997);

drop table Person;

create table Book
(
    book_id bigint generated by default as identity primary key,
    title varchar(255) not null,
    author varchar(255) not null unique,
    year_of_publication int2 not null,
    person_id bigint references Person(id)
);

insert into Book (title, author, year_of_publication, person_id)
values('The Hobbit', 'John Ronald Reuel Tolkien', 1937, 1);

drop table Book;